# Create this file in the root of your project: netlify.toml

[build]
  command = "echo 'No build command specified'"
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["*.json"]

[[redirects]]
  from = "/resume.json"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/projects.json"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/blogs.json"
  to = "/404.html"
  status = 404

# Force HTTPS for all requests
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Custom HTTP Headers for Security & Privacy
[[headers]]
  for = "/*"
  [headers.values]
    # Enhanced Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com;
      img-src 'self' data: https:;
      connect-src 'self' https://api.netlify.com;
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
      block-all-mixed-content"""

    # Prevents your site from being rendered in an iframe (clickjacking protection)
    X-Frame-Options = "DENY"

    # Prevents browsers from trying to guess the content type
    X-Content-Type-Options = "nosniff"

    # Enhanced referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Comprehensive Permissions Policy
    Permissions-Policy = """
      accelerometer=(),
      ambient-light-sensor=(),
      autoplay=(),
      camera=(),
      encrypted-media=(),
      fullscreen=(self),
      geolocation=(),
      gyroscope=(),
      magnetometer=(),
      microphone=(),
      midi=(),
      payment=(),
      picture-in-picture=(),
      speaker=(),
      usb=(),
      vibrate=(),
      vr=()"""

    # Permissions Policy (formerly Feature Policy)
    # Explicitly disable features not needed by your site.
    # Example: Deny access to microphone, camera, geolocation, etc.
    # Permissions-Policy = "camera=(), microphone=(), geolocation=()"

    # HTTP Strict Transport Security (HSTS)
    # Tells browsers to always connect to your site via HTTPS.
    # Start with a smaller max-age for testing, e.g., max-age=300.
    # Once confident, increase it. 'preload' is a bigger commitment.
    Strict-Transport-Security = "max-age=31536000; includeSubDomains" # 1 year

    # X-XSS-Protection (Largely deprecated by modern CSP, but harmless for older browser support)
    X-XSS-Protection = "1; mode=block" 