[build]
  command = "echo 'No build command specified'"
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["*.json"]

# [[redirects]]
#   from = "/resume.json"
#   to = "/404.html"
#   status = 404

# [[redirects]]
#   from = "/projects.json"
#   to = "/404.html"
#   status = 404



[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self' https://api.netlify.com; frame-src 'none'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), autoplay=(), camera=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), usb=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
